name: CI Pipeline

on: [push]

jobs:
  lint:
    name: Job 1 - Lint (Ruff)
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar Ruff
        run: python -m pip install ruff

      - name: Executar Ruff
        run: python -m ruff check