name: CI

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v6

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: python -m pip install -r requirements-dev.txt

      - name: Lint com Ruff
        run: python -m ruff check .
  teste_unitario:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo
        uses: actions/checkout@v6
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Testes com Pytest
        run: python -m pytest -v

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo
        uses: actions/checkout@v6
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Build com compileall
        run: python -m compileall -q app scripts tasks.py        
