name: CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v6

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: python -m pip install -r requirements-dev.txt

      - name: Lint com Ruff
        run: python -m ruff check .